# Generated by Django 3.1.7 on 2021-03-17 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField(blank=True, default='')),
                ('lon', models.FloatField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, default='POR_VALIDAR', max_length=20, null=True)),
                ('category', models.TextField(blank=True, max_length=20, null=True)),
                ('distance_from_hq', models.FloatField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'status'],
            },
        ),
    ]
