# Generated by Django 3.1.7 on 2021-03-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
